version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventapp-backend-jenkins
    ports:
      - "6000:5000"          # hostPort:containerPort -> changed to 6000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - event-net-jenkins

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventapp-frontend-jenkins
    ports:
      - "4000:80"            # hostPort:containerPort -> changed to 4000
    depends_on:
      - backend
    networks:
      - event-net-jenkins

  db:
    image: mysql:8.0
    container_name: eventapp-db-jenkins
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CUII@123456
      MYSQL_DATABASE: eventdb
    ports:
      - "3309:3306"          # hostPort:containerPort -> changed to 3309
    volumes:
      - db_data_jenkins:/var/lib/mysql
    networks:
      - event-net-jenkins

volumes:
  db_data_jenkins:

networks:
  event-net-jenkins:
